### ISSUE TITLE
Off-canvas menu responsiveness problem

### ISSUE THREAD

**Issue by inderpreetsingh** [cockroachdb/cockroachdb.github.io#3]
I was just going through the website, and found a little bug. If you, decrease the browser size, open off-canvas menu (one that's toggled by hamburger icon) and then maximize the browser again (without closing the menu), the off-canvas menu stays there without any option to close it (as shown in screenshot).

![screenshot from 2015-06-05 12 07 20](https://cloud.githubusercontent.com/assets/1131610/8000665/7ecb415c-0b7b-11e5-9d62-937aeea168d0.png)

**Comment by bdarnell** [comment]
This has been fixed.
